[requests.lse.personal]
ABDP = "Ab Dynamics PLC"
EZJ = "easyJet plc"
PPS = "Proton Motor Power Systems Plc"

[requests.lse.ftse]
AAL	= "Anglo American"
ABF	= "Associated British Foods"
ADM	= "Admiral"
AHT	= "Ashtead"
ANTO = "Antofagasta"
AUTO = "Auto Trader"
AV_	= "Aviva"
AVST = "Avast"
AVV	= "Aveva"
AZN	= "Astrazeneca"
BA_	= "BAE Systems"
BARC = "Barclays"
BATS = "BAT"
BDEV = "Barratt Developments"
BHP	= "BHP Group"
BKG	= "Berkeley"
BLND = "British Land"
BNZL = "Bunzl"
BP_	= "BP"
BRBY = "Burberry"
BT_A = "BT"
CCH	= "Coca Cola Hbc"
CPG	= "Compass"
CRDA = "Croda International"
CRH	= "CRH"
DCC	= "DCC"
DGE	= "Diageo"
EVR	= "Evraz"
EXPN = "Experian"
FERG = "Ferguson"
FLTR = "Flutter Entertainment"
FRES = "Fresnillo"
GLEN = "Glencore"
GSK	= "GlaxoSmithKline"
GVC	= "GVC"
HIK	= "Hikma Pharmaceuticals"
HL_	= "Hargreaves Lansdown"
HLMA = "Halma"
HSBA = "HSBC"
HSV	= "Homeserve"
IAG	= "Intl Consolidated Airlines"
ICP	= "Intermediate Capital"
IHG	= "Intercontinental Hotels"
III	= "3i"
IMB	= "Imperial Brands"
INF	= "Informa"
ITRK = "Intertek"
ITV	= "ITV"
JD_	= "JD Sports Fashion"
JET	= "Just Eat Takeaway.com"
JMAT = "Johnson Matthey"
KGF	= "Kingfisher"
LAND = "Land Securities"
LGEN = "Legal & General"
LLOY = "Lloyds Banking"
LSE	= "London Stock Exchange"
MNDI = "Mondi"
MNG	= "M&G"
MRO	= "Melrose Industries"
MRW	= "Morrison (Wm)"
NG_	= "National Grid"
NXT	= "Next"
OCDO = "Ocado"
PHNX = "Phoenix Group"
PNN	= "Pennon"
POLY = "Polymetal International"
PRU	= "Prudential"
PSN	= "Persimmon"
PSON = "Pearson"
RB_	= "Reckitt Benckiser"
RBS	= "Royal Bank of Scotland"
RDSA = "Royal Dutch Shell A"
RDSB = "Royal Dutch Shell B"
REL	= "Relx"
RIO	= "Rio Tinto"
RMV	= "Rightmove"
RR_	= "Rolls-Royce"
RSA	= "RSA Insurance"
RTO	= "Rentokil Initial"
SBRY = "Sainsbury (J)"
SDR	= "Schroders Vtg"
SGE	= "Sage"
SGRO = "Segro"
SKG	= "Smurfit Kappa"
SLA	= "Standard Life Aberdeen"
SMDS = "Smith (DS)"
SMIN = "Smiths Group"
SMT	= "Scottish Mortgage Inv Tst"
SN_	= "Smith & Nephew"
SPX	= "Spirax-Sarco Engineering"
SSE	= "SSE"
STAN = "Standard Chartered"
STJ	= "St James's Place"
SVT	= "Severn Trent"
TSCO = "Tesco"
TW_	= "Taylor Wimpey"
ULVR = "Unilever"
UU_	= "United Utilities"
VOD	= "Vodafone"
WPP	= "WPP"
